'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {SVGRenderer,SVGObject} from 'three/examples/jsm/renderers/SVGRenderer.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {buildScene,buildGraph,C,builder} from '@/lib/atlas/geometry';
import type {GraphSpec} from '@/lib/atlas/math';
import {RotateCcw,Maximize,Minimize,Move3D} from 'lucide-react';
function dispose(g:T.Object3D){g.traverse((o:any)=>{o.geometry?.dispose();const m=Array.isArray(o.material)?o.material:[o.material];for(const a of m){a?.map?.dispose();a?.dispose();}})}
export function Viewport({scene,parameter,graph,resetKey=0,onStatus}:{scene:string;parameter:number;graph?:GraphSpec;resetKey?:number;onStatus?:(s:string)=>void}){
 const host=useRef<HTMLDivElement>(null),api=useRef<any>(null);const [error,setError]=useState(''),[full,setFull]=useState(false),[fallback,setFallback]=useState(false);const status=useRef(onStatus);status.current=onStatus;
 useEffect(()=>{if(!host.current)return;const el=host.current;let renderer:any;let cpu=false;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});}catch{renderer=new SVGRenderer();renderer.setPrecision(2);cpu=true;setFallback(true);}
 renderer.setPixelRatio?.(Math.min(window.devicePixelRatio,2));if(cpu)renderer.setClearColor(new T.Color(0xeef3ff));else renderer.setClearColor(0xeef3ff,0);renderer.outputColorSpace=T.SRGBColorSpace;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D mathematical scene. Drag to orbit; use arrow keys to rotate and plus or minus to zoom.');renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('tabindex','0');
 const world=new T.Scene(),camera=new T.PerspectiveCamera(40,1,.01,10000);camera.up.set(0,0,1);camera.position.set(7,-9,7);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;controls.minDistance=.1;controls.maxDistance=5000;world.add(new T.AmbientLight(0xffffff,cpu?.55:1.7));const light=new T.DirectionalLight(0xcff7ff,cpu?.75:2.6);light.position.set(3,-4,8);world.add(light);const rim=new T.DirectionalLight(0x789cda,cpu?.35:1.6);rim.position.set(-5,2,4);world.add(rim);
 const content=new T.Group(),axes=new T.Group();world.add(content,axes);content.userData.lowQuality=cpu;let lastScene='';let dirty=true;
 const fit=()=>{const box=new T.Box3().setFromObject(content);if(box.isEmpty())box.setFromCenterAndSize(new T.Vector3(),new T.Vector3(4,4,4));const center=box.getCenter(new T.Vector3());const span=Math.max(...box.getSize(new T.Vector3()).toArray(),2);controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(1,-1.35,1).normalize().multiplyScalar(span*2.1));camera.near=Math.max(.001,span/1000);camera.far=Math.max(1000,span*100);camera.updateProjectionMatrix();controls.update();};
 const drawAxes=()=>{dispose(axes);axes.clear();const box=new T.Box3().setFromObject(content);const size=box.isEmpty()?3:Math.min(1000,Math.max(2,...box.getSize(new T.Vector3()).toArray())*.6);const s=Math.ceil(size),zs=Math.min(s,Math.max(1,box.max.z+.3));const {line,arrow}=builder(axes);for(let i=-5;i<=5;i++){const v=i*s/5;line([[-s,v,0],[s,v,0]],0xcbd6ea);line([[v,-s,0],[v,s,0]],0xcbd6ea);}arrow([0,0,0],[s,0,0],0xc97884);arrow([0,0,0],[0,s,0],0x83cfc2);arrow([0,0,0],[0,0,zs],0x90b0ee);for(const [name,pos,color]of [['x',[s+.14,0,0],'#bf4d59'],['y',[0,s+.14,0],'#237966'],['z',[0,0,zs+.14],'#345ab8']] as const){if(cpu){const text=document.createElementNS('http://www.w3.org/2000/svg','text');text.textContent=name;text.setAttribute('fill',color);text.setAttribute('font-size','17');text.setAttribute('font-style','italic');const label=new SVGObject(text);label.position.set(pos[0],pos[1],pos[2]);axes.add(label);continue;}const c=document.createElement('canvas');c.width=64;c.height=64;const ctx=c.getContext('2d')!;ctx.font='italic 40px Georgia';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(name,32,46);const tex=new T.CanvasTexture(c);const sprite=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:false}));sprite.position.set(pos[0],pos[1],pos[2]);sprite.scale.set(s*.12,s*.12,1);axes.add(sprite);}};
 api.current={content,fit,drawAxes,controls,camera,lastScene,markDirty:()=>{dirty=true}};controls.addEventListener('change',()=>{dirty=true});const resize=new ResizeObserver(()=>{const {width,height}=el.getBoundingClientRect();if(!width||!height)return;renderer.setSize(width,height);dirty=true;camera.aspect=width/height;camera.updateProjectionMatrix();});resize.observe(el);let frame=0;const render=()=>{frame=requestAnimationFrame(render);controls.update();if(dirty){renderer.render(world,camera);dirty=false;const done=api.current?.afterFrame;if(done){api.current.afterFrame=null;done();}}};render();
 const key=(e:KeyboardEvent)=>{const offset=camera.position.clone().sub(controls.target);if(e.key==='ArrowLeft'||e.key==='ArrowRight'){offset.applyAxisAngle(new T.Vector3(0,0,1),e.key==='ArrowLeft'?.12:-.12);}else if(e.key==='ArrowUp'||e.key==='ArrowDown'){offset.applyAxisAngle(new T.Vector3().crossVectors(offset,new T.Vector3(0,0,1)).normalize(),e.key==='ArrowUp'?.1:-.1);}else if(e.key==='+'||e.key==='=')offset.multiplyScalar(.9);else if(e.key==='-')offset.multiplyScalar(1.1);else return;e.preventDefault();camera.position.copy(controls.target).add(offset);controls.update();};renderer.domElement.addEventListener('keydown',key);
 return()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();dispose(world);renderer.dispose?.();renderer.domElement.remove();api.current=null;};
 },[]);
 useEffect(()=>{const a=api.current;if(!a)return;dispose(a.content);a.content.clear();try{const report=graph?buildGraph(graph,a.content):buildScene(scene,parameter,a.content);setError('');a.afterFrame=()=>status.current?.(report||'Scene rendered');const key=scene+(graph?JSON.stringify({...graph,a:0}):'');if(a.lastScene!==key){a.drawAxes();a.fit();a.lastScene=key;}a.markDirty();}catch(e){setError((e as Error).message);status.current?.('Error: '+(e as Error).message);}},[scene,parameter,graph]);
 useEffect(()=>{api.current?.fit();},[resetKey]);
 useEffect(()=>{const fn=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn)},[]);
 return <div className={'viewport-shell'+(full?' expanded':'')}><div className="viewport-top"><span><Move3D size={15}/> 3D EXPLORATION{fallback?' · COMPATIBILITY MODE':''}</span><div><button aria-label="Reset camera" onClick={()=>api.current?.fit()} title="Reset camera"><RotateCcw size={17}/></button><button aria-label={full?'Exit fullscreen':'Fullscreen visualization'} onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else host.current?.closest('.experience')?.requestFullscreen?.();}} title="Fullscreen">{full?<Minimize size={17}/>:<Maximize size={17}/>}</button></div></div><div ref={host} className="canvas-host"/>{error&&<div className="scene-error" role="alert">{error}</div>}<div className="orbit-hint">Drag to orbit <span>·</span> Scroll or pinch to zoom <span>·</span> Arrow keys to rotate</div></div>
}
